//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalInfo
    {
        public int AInfID { get; set; }
        public string JoiningDate { get; set; }
        public string Rank { get; set; }
        public string Position { get; set; }
        public string LPRDate { get; set; }
        public string Cadre { get; set; }
        public System.DateTime CadreDate { get; set; }
        public int userId { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
