//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Award
    {
        public int AwardId { get; set; }

        [Required(ErrorMessage = "Enter Award Title Please")]
        public string TitleOfaward { get; set; }

        [Required(ErrorMessage = "Enter Ground Please")]
        public string Ground { get; set; }

        [Required(ErrorMessage = "Enter Award Date")]
        public System.DateTime Date { get; set; }

        [Required(ErrorMessage = "Must Be Select User Name")]
        public Nullable<int> UserId { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
