//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ChildrenInfo
    {
        public int ChildrenInfoId { get; set; }

        [Required(ErrorMessage = "Enter Children Name")]
        public string ChildrenName { get; set; }

        [Required(ErrorMessage = "Enter Date of Birth")]
        public string ChildrenDOB { get; set; }

        [Required(ErrorMessage = "Select Gender")]
        public string ChildrenSex { get; set; }
        [Required(ErrorMessage = "Must be Select User Name")]
        public int userId { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
