//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EducationalInfo
    {
        public int EducationalQId { get; set; }

        [Required(ErrorMessage = "Enter Degree Title")]
        public string DegreeTitel { get; set; }

        [Required(ErrorMessage = "Enter Institute Name")]
        public string InstituteName { get; set; }

        [Required(ErrorMessage = "Enter Passing Year")]
        public string PassingYear { get; set; }

        [Required(ErrorMessage = "Enter Principle Subject")]
        public string PrincicpalSubject { get; set; }

        [Required(ErrorMessage = "Enter Your Result")]
        public string Result { get; set; }

        [Required(ErrorMessage = "Must be Select User Name")]
        public int UserId { get; set; }

        public string Board { get; set; }

        [Required(ErrorMessage = "Enter Out Of Result GPA/CGPA")]
        public string OutOf { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
