//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ForeignTravle
    {
        public int ForeignTravelId { get; set; }

        [Required(ErrorMessage = "Enter Country")]
        public string Country { get; set; }

        [Required(ErrorMessage = "Enter the Purpuse")]
        public string Purpuse { get; set; }

        [Required(ErrorMessage = "Enter Troble From")]
        public string TFrom { get; set; }

        [Required(ErrorMessage = "Enter Travle To")]
        public string TTo { get; set; }

        [Required(ErrorMessage = "Must be select user name")]
        public int userId { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
