//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class GeneralInfo
    {
        public int GeneralInfoID { get; set; }

        [Required(ErrorMessage = "Enter User Name")]
        public string Name { get; set; }

        
        public string FathersName { get; set; }

        
        public string MothersName { get; set; }

        [Required(ErrorMessage = "Enter Select Date")]
        public System.DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "Enter User Nationality")]
        public string Nationality { get; set; }

        [Required(ErrorMessage = "Enter User NID Number")]
        [StringLength(20, MinimumLength = 10, ErrorMessage = "length is 10 to 13")]
        public string NIDNumber { get; set; }

        [Required(ErrorMessage = "Select Gender")]
        public string Gender { get; set; }

        
        public string BloodGroup { get; set; }

        [Required(ErrorMessage = "Mobile Is Required")]
        [StringLength(13, MinimumLength = 10, ErrorMessage = "length is 10 to 13")]
        public string ContactPhone { get; set; }

        
        public string CellPhone { get; set; }


        [Required(ErrorMessage = "Religion Required")]
        public string Religion { get; set; }


        [Required(ErrorMessage = "Email Is Requeird")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$")]
        public string Email { get; set; }


        [Required(ErrorMessage = "Present Address Required")]
        public string PresentAddress { get; set; }

        [Required(ErrorMessage = "Permanent Address Required")]
        public string PermanentAddress { get; set; }

        [Required(ErrorMessage = "District Required")]
        public string HomeDistrict { get; set; }

        [Required(ErrorMessage = "Select Marital Status")]
        public string MarialStatus { get; set; }

       
        public string SpouseName { get; set; }

      
        public string SpouseOccopation { get; set; }

       
        public string SpouseDesignation { get; set; }

        
        public string SpouseHomeDistrict { get; set; }

        
        public string SpouseOrganization { get; set; }

        
        public string SpouseOrgLocation { get; set; }

        [Required(ErrorMessage = "Joining Date required")]
        public Nullable<System.DateTime> JoiningDate { get; set; }

        [Required(ErrorMessage = "Rank Required")]
        public string Rank { get; set; }

        [Required(ErrorMessage = "Position Required")]
        public string Position { get; set; }

        [Required(ErrorMessage = "Select LPR Date")]
        public Nullable<System.DateTime> LPRDate { get; set; }



        [Required(ErrorMessage = "Select Cadre")]
        public string Cadre { get; set; }

        
        public Nullable<System.DateTime> CadreDate { get; set; }

        
        public string CadreBatch { get; set; }

        [Required(ErrorMessage = "Must be select User Id")]
        public int userId { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
