//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRM_DatabaseEntities : DbContext
    {
        public HRM_DatabaseEntities()
            : base("name=HRM_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalInfo> AdditionalInfoes { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<ChildrenInfo> ChildrenInfoes { get; set; }
        public virtual DbSet<EducationalInfo> EducationalInfoes { get; set; }
        public virtual DbSet<ForeignTravle> ForeignTravles { get; set; }
        public virtual DbSet<GeneralInfo> GeneralInfoes { get; set; }
        public virtual DbSet<LanguageInfo> LanguageInfoes { get; set; }
        public virtual DbSet<OthersService> OthersServices { get; set; }
        public virtual DbSet<PostingAddress> PostingAddresses { get; set; }
        public virtual DbSet<PostingRecord> PostingRecords { get; set; }
        public virtual DbSet<PromotionalParticular> PromotionalParticulars { get; set; }
        public virtual DbSet<PromotionalP> PromotionalPs { get; set; }
        public virtual DbSet<Publication> Publications { get; set; }
        public virtual DbSet<ServiceHistory> ServiceHistories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrainingInfo> TrainingInfoes { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    }
}
