//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LanguageInfo
    {
        public int LanguageId { get; set; }

        [Required (ErrorMessage="Select User Reading Skills")]
        public string ReadSkills { get; set; }

        [Required (ErrorMessage="Select user writing Skills")]
        public string WriteSkills { get; set; }

        [Required(ErrorMessage = "Select Speak Skills")]
        public string SpeakSkills { get; set; }


        [Required(ErrorMessage = "Must Be Select Userid")]
        public int Userid { get; set; }


        [Required(ErrorMessage = "Muset Be Select User Id")]
        public string Language { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
