//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PostingAddress
    {
        public int PaId { get; set; }


        [Required(ErrorMessage = "Muset be Select user Id")]
        public int UserId { get; set; }


        [Required(ErrorMessage = "Post reqired")]
        public string Post { get; set; }


        [Required(ErrorMessage = "Organaization Required")]
        public string Organization { get; set; }


        [Required(ErrorMessage = "Enter Country")]
        public string Country { get; set; }

        [Required(ErrorMessage = "Posting From Required")]
        public string PaFom { get; set; }

        [Required(ErrorMessage = "Posting Address To Required")]
        public string PaTo { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
