//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PostingRecord
    {
        public int PostingId { get; set; }

        [Required (ErrorMessage="Organization Required")]
        public string Organization { get; set; }

        [Required(ErrorMessage = "Organization Required")]
        public string Location { get; set; }

        [Required(ErrorMessage = "Thana Required")]
        public string Thana { get; set; }

        [Required(ErrorMessage = "District Required")]
        public string District { get; set; }

        [Required(ErrorMessage ="Enter Posting From")]
        public string Pfrom { get; set; }

        [Required(ErrorMessage = "Enter Posting To")]
        public string PTo { get; set; }

        [Required(ErrorMessage = "Pay Scal Required")]
        public string PayScal { get; set; }

        [Required(ErrorMessage = "Posting Date Required")]
        public System.DateTime PostingDate { get; set; }

        //[Required(ErrorMessage = "Country Required")]
        public string Country { get; set; }

        [Required(ErrorMessage = "Must be Select user Id")]
        public int userId { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
