//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceHistory
    {
        public int SHId { get; set; }
        public int UserId { get; set; }
        public System.DateTime GovtServiceDate { get; set; }
        public System.DateTime GazetteDate { get; set; }
        public Nullable<System.DateTime> SeniorDate { get; set; }
        public string Encaderment { get; set; }
        public string CadreBCS { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
