//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TrainingInfo
    {
        public int TrainingId { get; set; }

        [Required(ErrorMessage = "Training Location Required")]
        public string TrainingLocation { get; set; }

        [Required(ErrorMessage = "Course Required")]
        public string Course { get; set; }

        [Required(ErrorMessage = "Title Required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Institute Required")]
        public string Institute { get; set; }

        [Required(ErrorMessage = "Grade Required")]
        public string Grade { get; set; }

        [Required(ErrorMessage = "Position Required")]
        public string Position { get; set; }

        [Required(ErrorMessage = "Country Required")]
        public string Country { get; set; }

        [Required(ErrorMessage = "Muset be Select user Id")]
        public int UserId { get; set; }

        [Required(ErrorMessage = "Enter Training Type")]
        public string TrainingType { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
