//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinistryOfLand.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.AdditionalInfoes = new HashSet<AdditionalInfo>();
            this.Awards = new HashSet<Award>();
            this.ChildrenInfoes = new HashSet<ChildrenInfo>();
            this.EducationalInfoes = new HashSet<EducationalInfo>();
            this.ForeignTravles = new HashSet<ForeignTravle>();
            this.GeneralInfoes = new HashSet<GeneralInfo>();
            this.LanguageInfoes = new HashSet<LanguageInfo>();
            this.OthersServices = new HashSet<OthersService>();
            this.PostingAddresses = new HashSet<PostingAddress>();
            this.PostingRecords = new HashSet<PostingRecord>();
            this.PromotionalParticulars = new HashSet<PromotionalParticular>();
            this.PromotionalPs = new HashSet<PromotionalP>();
            this.Publications = new HashSet<Publication>();
            this.ServiceHistories = new HashSet<ServiceHistory>();
            this.TrainingInfoes = new HashSet<TrainingInfo>();
        }
    
        public int userId { get; set; }
         //[Required(ErrorMessage = "User Name Required*")]
        public string username { get; set; }
         //[Required(ErrorMessage = "Password Required*")]
        public string password { get; set; }
        public string email { get; set; }
        public string UserType { get; set; }
        public string UserImage { get; set; }
    
        public virtual ICollection<AdditionalInfo> AdditionalInfoes { get; set; }
        public virtual ICollection<Award> Awards { get; set; }
        public virtual ICollection<ChildrenInfo> ChildrenInfoes { get; set; }
        public virtual ICollection<EducationalInfo> EducationalInfoes { get; set; }
        public virtual ICollection<ForeignTravle> ForeignTravles { get; set; }
        public virtual ICollection<GeneralInfo> GeneralInfoes { get; set; }
        public virtual ICollection<LanguageInfo> LanguageInfoes { get; set; }
        public virtual ICollection<OthersService> OthersServices { get; set; }
        public virtual ICollection<PostingAddress> PostingAddresses { get; set; }
        public virtual ICollection<PostingRecord> PostingRecords { get; set; }
        public virtual ICollection<PromotionalParticular> PromotionalParticulars { get; set; }
        public virtual ICollection<PromotionalP> PromotionalPs { get; set; }
        public virtual ICollection<Publication> Publications { get; set; }
        public virtual ICollection<ServiceHistory> ServiceHistories { get; set; }
        public virtual ICollection<TrainingInfo> TrainingInfoes { get; set; }
    }
}
